// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutcompanyDocumentDataSlicesSlice =
  | HowWeWorkSlice
  | ImplementationSlice
  | ApproachSlice
  | ApplicationSlice
  | BrandSlice;

/**
 * Content for AboutCompany documents
 */
interface AboutcompanyDocumentData {
  /**
   * Slice Zone field in *AboutCompany*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutcompany.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutcompanyDocumentDataSlicesSlice> /**
   * Meta Title field in *AboutCompany*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: aboutcompany.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *AboutCompany*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: aboutcompany.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *AboutCompany*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutcompany.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * title field in *AboutCompany*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutcompany.title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * AboutCompany document from Prismic
 *
 * - **API ID**: `aboutcompany`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutcompanyDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<AboutcompanyDocumentData>,
  "aboutcompany",
  Lang
>;

/**
 * Item in *Cases → list*
 */
export interface CaseDocumentDataListItem {
  /**
   * item title field in *Cases → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case.list[].list_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_title: prismic.RichTextField;

  /**
   * item_text field in *Cases → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case.list[].list_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_text: prismic.RichTextField;
}

/**
 * Item in *Cases → list_images*
 */
export interface CaseDocumentDataListImagesItem {
  /**
   * item_image field in *Cases → list_images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case.list_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type CaseDocumentDataSlicesSlice = never;

/**
 * Content for Cases documents
 */
interface CaseDocumentData {
  /**
   * title field in *Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * main image field in *Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * list field in *Cases*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case.list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<CaseDocumentDataListItem>>;

  /**
   * list_images field in *Cases*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case.list_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_images: prismic.GroupField<Simplify<CaseDocumentDataListImagesItem>>;

  /**
   * Slice Zone field in *Cases*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: case.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CaseDocumentDataSlicesSlice> /**
   * Meta Title field in *Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: case.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: case.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Cases document from Prismic
 *
 * - **API ID**: `case`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<CaseDocumentData>,
  "case",
  Lang
>;

type ContactDocumentDataSlicesSlice = MapSlice | ApplicationSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ContactDocumentData>,
  "contact",
  Lang
>;

type HomeDocumentDataSlicesSlice = ReviewsSlice | BannerSlice | GetPrintSlice | ApplicationSlice | ApproachSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HomeDocumentData>,
  "home",
  Lang
>;

/**
 * Item in *navigation → list*
 */
export interface NavigationDocumentDataListItem {
  /**
   * link field in *navigation → list*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.list[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type NavigationDocumentDataSlicesSlice = never;

/**
 * Content for navigation documents
 */
interface NavigationDocumentData {
  /**
   * list field in *navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<NavigationDocumentDataListItem>>;

  /**
   * logoLink field in *navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logolink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logolink: prismic.LinkField;

  /**
   * logo field in *navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<NavigationDocumentData>,
  "navigation",
  Lang
>;

type PortfolioDocumentDataSlicesSlice = ApplicationSlice;

/**
 * Content for portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * title field in *portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Title field in *portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<PortfolioDocumentData>,
  "portfolio",
  Lang
>;

type ProductDocumentDataSlicesSlice = never;

/**
 * Content for product documents
 */
interface ProductDocumentData {
  /**
   * title field in *product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * product image field in *product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Title field in *product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ProductDocumentData>,
  "product",
  Lang
>;

type ServicesDocumentDataSlicesSlice = ApplicationSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ServicesDocumentData>,
  "services",
  Lang
>;

export type AllDocumentTypes =
  | AboutcompanyDocument
  | CaseDocument
  | ContactDocument
  | HomeDocument
  | NavigationDocument
  | PortfolioDocument
  | ProductDocument
  | ServicesDocument;

/**
 * Primary content in *Application → Default → Primary*
 */
export interface ApplicationSliceDefaultPrimary {
  /**
   * title field in *Application → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Application → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *Application → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: application.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * app store link field in *Application → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: application.default.primary.app_store_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  app_store_link: prismic.LinkField;

  /**
   * google store link field in *Application → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: application.default.primary.google_store_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  google_store_link: prismic.LinkField;

  /**
   * image arrow field in *Application → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: application.default.primary.image_arrow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_arrow: prismic.ImageField<never>;
}

/**
 * Default variation for Application Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApplicationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ApplicationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Application*
 */
type ApplicationSliceVariation = ApplicationSliceDefault;

/**
 * Application Shared Slice
 *
 * - **API ID**: `application`
 * - **Description**: Application
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApplicationSlice = prismic.SharedSlice<"application", ApplicationSliceVariation>;

/**
 * Primary content in *Approach → Default → Primary*
 */
export interface ApproachSliceDefaultPrimary {
  /**
   * text field in *Approach → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: approach.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * title field in *Approach → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: approach.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for Approach Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApproachSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ApproachSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Approach*
 */
type ApproachSliceVariation = ApproachSliceDefault;

/**
 * Approach Shared Slice
 *
 * - **API ID**: `approach`
 * - **Description**: Approach
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApproachSlice = prismic.SharedSlice<"approach", ApproachSliceVariation>;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Banner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * arrow field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.arrow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  arrow: prismic.ImageField<never>;

  /**
   * text_link field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.text_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_link: prismic.KeyTextField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BannerSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Item in *Brand → Default → Primary → list*
 */
export interface BrandSliceDefaultPrimaryListItem {
  /**
   * title field in *Brand → Default → Primary → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.default.primary.list[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Brand → Default → Primary → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.default.primary.list[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *Brand → Default → Primary → list*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.default.primary.list[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Brand → Default → Primary*
 */
export interface BrandSliceDefaultPrimary {
  /**
   * list field in *Brand → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: brand.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<BrandSliceDefaultPrimaryListItem>>;
}

/**
 * Default variation for Brand Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BrandSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Brand*
 */
type BrandSliceVariation = BrandSliceDefault;

/**
 * Brand Shared Slice
 *
 * - **API ID**: `brand`
 * - **Description**: Brand
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandSlice = prismic.SharedSlice<"brand", BrandSliceVariation>;

/**
 * Primary content in *GetPrint → Default → Primary*
 */
export interface GetPrintSliceDefaultPrimary {
  /**
   * title field in *GetPrint → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: У меня есть дизайн
   * - **API ID Path**: get_print.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * title_text field in *GetPrint → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: хочу заказать печать
   * - **API ID Path**: get_print.default.primary.title_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_text: prismic.KeyTextField;

  /**
   * buttonText field in *GetPrint → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Свяжитесь со мной
   * - **API ID Path**: get_print.default.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttontext: prismic.KeyTextField;

  /**
   * arrow field in *GetPrint → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: get_print.default.primary.arrow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  arrow: prismic.ImageField<never>;
}

/**
 * Default variation for GetPrint Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetPrintSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GetPrintSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GetPrint*
 */
type GetPrintSliceVariation = GetPrintSliceDefault;

/**
 * GetPrint Shared Slice
 *
 * - **API ID**: `get_print`
 * - **Description**: GetPrint
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetPrintSlice = prismic.SharedSlice<"get_print", GetPrintSliceVariation>;

/**
 * Item in *HowWeWork → Default → Primary → list*
 */
export interface HowWeWorkSliceDefaultPrimaryListItem {
  /**
   * text_teg field in *HowWeWork → Default → Primary → list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.list[].text_teg
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_teg: prismic.KeyTextField;

  /**
   * title_box field in *HowWeWork → Default → Primary → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.list[].title_box
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_box: prismic.RichTextField;

  /**
   * text_box field in *HowWeWork → Default → Primary → list*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.list[].text_box
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_box: prismic.RichTextField;
}

/**
 * Primary content in *HowWeWork → Default → Primary*
 */
export interface HowWeWorkSliceDefaultPrimary {
  /**
   * title field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text_center field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.text_center
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_center: prismic.RichTextField;

  /**
   * image_box field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image_box
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_box: prismic.ImageField<never>;

  /**
   * list field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<HowWeWorkSliceDefaultPrimaryListItem>>;
}

/**
 * Default variation for HowWeWork Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowWeWorkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowWeWorkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HowWeWork*
 */
type HowWeWorkSliceVariation = HowWeWorkSliceDefault;

/**
 * HowWeWork Shared Slice
 *
 * - **API ID**: `how_we_work`
 * - **Description**: HowWeWork
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowWeWorkSlice = prismic.SharedSlice<"how_we_work", HowWeWorkSliceVariation>;

/**
 * Item in *Implementation → Default → Primary → list*
 */
export interface ImplementationSliceDefaultPrimaryListItem {
  /**
   * image field in *Implementation → Default → Primary → list*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: implementation.default.primary.list[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Implementation → Default → Primary*
 */
export interface ImplementationSliceDefaultPrimary {
  /**
   * text field in *Implementation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: implementation.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * title field in *Implementation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: implementation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtext field in *Implementation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: implementation.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtext: prismic.RichTextField;

  /**
   * list field in *Implementation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: implementation.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<ImplementationSliceDefaultPrimaryListItem>>;
}

/**
 * Default variation for Implementation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImplementationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImplementationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Implementation*
 */
type ImplementationSliceVariation = ImplementationSliceDefault;

/**
 * Implementation Shared Slice
 *
 * - **API ID**: `implementation`
 * - **Description**: Implementation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImplementationSlice = prismic.SharedSlice<"implementation", ImplementationSliceVariation>;

/**
 * Primary content in *Map → Default → Primary*
 */
export interface MapSliceDefaultPrimary {
  /**
   * map field in *Map → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.map
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  map: prismic.GeoPointField;

  /**
   * adress field in *Map → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.adress
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  adress: prismic.KeyTextField;

  /**
   * text field in *Map → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * mail field in *Map → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.mail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mail: prismic.LinkField;

  /**
   * text_mail field in *Map → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.text_mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_mail: prismic.KeyTextField;

  /**
   * text_problem field in *Map → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.text_problem
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_problem: prismic.KeyTextField;

  /**
   * link_phone field in *Map → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.link_phone
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_phone: prismic.LinkField;

  /**
   * text_phone field in *Map → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.text_phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_phone: prismic.KeyTextField;

  /**
   * time_work field in *Map → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.time_work
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time_work: prismic.KeyTextField;

  /**
   * green_arrow field in *Map → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: map.default.primary.green_arrow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  green_arrow: prismic.ImageField<never>;
}

/**
 * Default variation for Map Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MapSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Map*
 */
type MapSliceVariation = MapSliceDefault;

/**
 * Map Shared Slice
 *
 * - **API ID**: `map`
 * - **Description**: Map
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSlice = prismic.SharedSlice<"map", MapSliceVariation>;

/**
 * Item in *Reviews → Default → Primary → list_reviews*
 */
export interface ReviewsSliceDefaultPrimaryListReviewsItem {
  /**
   * client_text field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].client_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  client_text: prismic.RichTextField;

  /**
   * service_text field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].service_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_name: prismic.RichTextField;

  /**
   * what_make_text field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].what_make_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  what_make_text: prismic.RichTextField;

  /**
   * direction_text field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].direction_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  direction_text: prismic.RichTextField;

  /**
   * feedback_text field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].feedback_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feedback_text: prismic.RichTextField;

  /**
   * image field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link_case field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].link_case
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_case: prismic.LinkField;

  /**
   * link_text field in *Reviews → Default → Primary → list_reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Primary content in *Reviews → Default → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
  /**
   * title field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * link_portfolio field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.link_portfolio
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_portfolio: prismic.LinkField;

  /**
   * arrow_link field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.arrow_link
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  arrow_link: prismic.ImageField<never>;

  /**
   * link_portfolio_text field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.link_portfolio_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_portfolio_text: prismic.KeyTextField;

  /**
   * arrow_top field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.arrow_top
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  arrow_top: prismic.ImageField<never>;

  /**
   * list_reviews field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.list_reviews[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_reviews: prismic.GroupField<Simplify<ReviewsSliceDefaultPrimaryListReviewsItem>>;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ReviewsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault;

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<"reviews", ReviewsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutcompanyDocument,
      AboutcompanyDocumentData,
      AboutcompanyDocumentDataSlicesSlice,
      CaseDocument,
      CaseDocumentData,
      CaseDocumentDataListItem,
      CaseDocumentDataListImagesItem,
      CaseDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataListItem,
      NavigationDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      ApplicationSlice,
      ApplicationSliceDefaultPrimary,
      ApplicationSliceVariation,
      ApplicationSliceDefault,
      ApproachSlice,
      ApproachSliceDefaultPrimary,
      ApproachSliceVariation,
      ApproachSliceDefault,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BrandSlice,
      BrandSliceDefaultPrimaryListItem,
      BrandSliceDefaultPrimary,
      BrandSliceVariation,
      BrandSliceDefault,
      GetPrintSlice,
      GetPrintSliceDefaultPrimary,
      GetPrintSliceVariation,
      GetPrintSliceDefault,
      HowWeWorkSlice,
      HowWeWorkSliceDefaultPrimaryListItem,
      HowWeWorkSliceDefaultPrimary,
      HowWeWorkSliceVariation,
      HowWeWorkSliceDefault,
      ImplementationSlice,
      ImplementationSliceDefaultPrimaryListItem,
      ImplementationSliceDefaultPrimary,
      ImplementationSliceVariation,
      ImplementationSliceDefault,
      MapSlice,
      MapSliceDefaultPrimary,
      MapSliceVariation,
      MapSliceDefault,
      ReviewsSlice,
      ReviewsSliceDefaultPrimaryListReviewsItem,
      ReviewsSliceDefaultPrimary,
      ReviewsSliceVariation,
      ReviewsSliceDefault,
    };
  }
}
