import "./globals.css";

import type { Metadata } from "next";

import Footer from "./components/shared/footer/Footer";
import Header from "./components/shared/header/Header";

export const metadata: Metadata = {
  title: "Astek",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", type: "image/png", sizes: "96x96", url: "/favicon-96x96.png" },
      { rel: "icon", type: "image/svg+xml", url: "/favicon.svg" },
    ],
    shortcut: { rel: "shortcut icon", url: "/favicon.ico" },
    apple: { rel: "apple-touch-icon", sizes: "180x180", url: "/apple-touch-icon.png" },
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body>
        <Header />
        <main className='m-auto max-w-[1920px] px-5'> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
