// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  application: dynamic(() => import("./Application")),
  approach: dynamic(() => import("./Approach")),
  banner: dynamic(() => import("./Banner")),
  brand: dynamic(() => import("./Brand")),
  get_print: dynamic(() => import("./GetPrint")),
  how_we_work: dynamic(() => import("./HowWeWork")),
  implementation: dynamic(() => import("./Implementation")),
  map: dynamic(() => import("./Map")),
  products_list: dynamic(() => import("./ProductsList")),
  reviews: dynamic(() => import("./Reviews")),
  types_of_work: dynamic(() => import("./TypesOfWork")),
};
